version: '3.7'

volumes:
    mysql_data:

services:
    database_libary:
        container_name: 'libary_db'
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        image: mysql:latest
        env_file: .env
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
