version: '3.7'

volumes:
    postgres:

services:
    postgres:
        container_name: library_postgres
        image: postgis/postgis:13-3.1-alpine
        restart: always
        env_file: 
            - .env
        ports:
            - "5432:5432"
        volumes:
            - postgres:/data/postgres
            - .docker/init/postgres/init_db/1_init_db.sh:/docker-entrypoint-initdb.d/1_init_db.sh
